// Generated by BUCKLESCRIPT VERSION 1.10.3, PLEASE EDIT WITH CARE
'use strict';

var Block       = require("bs-platform/lib/js/block.js");
var Picture     = require("interactive-pictures/src/picture.js");
var Interaction = require("interactive-pictures/src/interaction.js");

var view = Picture.picture(/* tuple */[
      1000,
      600
    ], /* :: */[
      /* Circle */Block.__(0, [
          /* tuple */[
            100,
            100
          ],
          50,
          /* Pink */4
        ]),
      /* :: */[
        /* Rect */Block.__(1, [
            /* tuple */[
              100,
              100
            ],
            300,
            20,
            /* Purple */6
          ]),
        /* :: */[
          /* Line */Block.__(2, [
              /* tuple */[
                100,
                50
              ],
              /* tuple */[
                600,
                100
              ],
              3,
              /* Green */2
            ]),
          /* :: */[
            /* Arrow */Block.__(3, [
                /* tuple */[
                  100,
                  50
                ],
                /* tuple */[
                  200,
                  200
                ],
                2,
                /* Black */8
              ]),
            /* :: */[
              /* Polygon */Block.__(4, [
                  /* :: */[
                    /* tuple */[
                      120,
                      150
                    ],
                    /* :: */[
                      /* tuple */[
                        100,
                        180
                      ],
                      /* :: */[
                        /* tuple */[
                          120,
                          190
                        ],
                        /* :: */[
                          /* tuple */[
                            130,
                            200
                          ],
                          /* :: */[
                            /* tuple */[
                              150,
                              160
                            ],
                            /* [] */0
                          ]
                        ]
                      ]
                    ]
                  ],
                  /* Blue */7
                ]),
              /* :: */[
                /* Polyline */Block.__(5, [
                    /* :: */[
                      /* tuple */[
                        120,
                        250
                      ],
                      /* :: */[
                        /* tuple */[
                          100,
                          280
                        ],
                        /* :: */[
                          /* tuple */[
                            120,
                            290
                          ],
                          /* :: */[
                            /* tuple */[
                              130,
                              300
                            ],
                            /* :: */[
                              /* tuple */[
                                150,
                                260
                              ],
                              /* [] */0
                            ]
                          ]
                        ]
                      ]
                    ],
                    /* Green */2
                  ]),
                /* :: */[
                  /* Image */Block.__(6, [
                      /* tuple */[
                        120,
                        350
                      ],
                      130,
                      130,
                      "http://cdn2-www.dogtime.com/assets/uploads/2010/12/puppies.jpg"
                    ]),
                  /* :: */[
                    /* Text */Block.__(7, [
                        /* tuple */[
                          320,
                          350
                        ],
                        "Hello"
                      ]),
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var main = Interaction.draw(view);

var P = 0;

exports.P    = P;
exports.view = view;
exports.main = main;
/* view Not a pure module */
