// Generated by BUCKLESCRIPT VERSION 1.10.3, PLEASE EDIT WITH CARE
'use strict';

var Web_document              = require("bucklescript-tea/src/web_document.js");
var Interact_ex$PhysicsSunset = require("./interact_ex.bs.js");

var partial_arg = Web_document.getElementById("root");

function app(param) {
  return Interact_ex$PhysicsSunset.main(partial_arg, param);
}

app(/* () */0);

exports.app = app;
/* partial_arg Not a pure module */
