// Generated by BUCKLESCRIPT VERSION 1.10.3, PLEASE EDIT WITH CARE
'use strict';

var Block       = require("bs-platform/lib/js/block.js");
var Picture     = require("interactive-pictures/src/picture.js");
var Tea_html    = require("bucklescript-tea/src/tea_html.js");
var Pervasives  = require("bs-platform/lib/js/pervasives.js");
var Interaction = require("interactive-pictures/src/interaction.js");

function setShift(param_0) {
  return /* SetShift */Block.__(0, [param_0]);
}

function tick(param_0) {
  return /* Tick */Block.__(1, [param_0]);
}

function setSimRate(param_0) {
  return /* SetSimRate */Block.__(2, [param_0]);
}

function viewPerson(p) {
  var mood = p[/* base_mood */0] + p[/* mood_swing */1] | 0;
  var match = +(mood < 100);
  var color;
  if (match !== 0) {
    color = /* Orange */3;
  } else {
    var match$1 = +(mood < 150);
    color = match$1 !== 0 ? /* Pink */4 : /* Red */0;
  }
  var r = Pervasives.max(10 + mood | 0, 10);
  var match_000 = 250 + p[/* shift */2] | 0;
  var head_000 = /* tuple */[
    match_000,
    260
  ];
  var head = /* Circle */Block.__(0, [
      head_000,
      r,
      color
    ]);
  return Picture.picture(/* tuple */[
              1000,
              600
            ], /* :: */[
              head,
              /* [] */0
            ]);
}

function view(param) {
  var simRate = param[/* simRate */1];
  var person = param[/* person */0];
  return Tea_html.div(/* None */0, /* None */0, /* [] */0, /* :: */[
              Tea_html.div(/* None */0, /* None */0, /* [] */0, /* :: */[
                    Tea_html.text(" Model: " + (String(person) + ("  :: Simulation Rate:: " + (String(simRate) + " ")))),
                    /* [] */0
                  ]),
              /* :: */[
                Tea_html.button(/* None */0, /* None */0, /* :: */[
                      Tea_html.onClick(/* Inc */0),
                      /* [] */0
                    ], /* :: */[
                      Tea_html.text("Inc Base_Mood"),
                      /* [] */0
                    ]),
                /* :: */[
                  Tea_html.button(/* None */0, /* None */0, /* :: */[
                        Tea_html.onClick(/* Dec */1),
                        /* [] */0
                      ], /* :: */[
                        Tea_html.text("Dec Base_Mood"),
                        /* [] */0
                      ]),
                  /* :: */[
                    Interaction.selector("Model Shift", /* :: */[
                          0,
                          /* :: */[
                            20,
                            /* :: */[
                              50,
                              /* :: */[
                                100,
                                /* :: */[
                                  200,
                                  /* [] */0
                                ]
                              ]
                            ]
                          ]
                        ], person[/* shift */2], setShift),
                    /* :: */[
                      Interaction.slider("Simulation Rate", 1, 10, simRate, setSimRate),
                      /* :: */[
                        viewPerson(person),
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

function tickPerson(t, p) {
  var delta = 120 * Math.sin(t / 250) | 0;
  return /* record */[
          /* base_mood */p[/* base_mood */0],
          /* mood_swing */delta,
          /* shift */p[/* shift */2]
        ];
}

function update(model, msg) {
  if (typeof msg === "number") {
    if (msg) {
      var init = model[/* person */0];
      return /* record */[
              /* person : record */[
                /* base_mood */model[/* person */0][/* base_mood */0] - 40 | 0,
                /* mood_swing */init[/* mood_swing */1],
                /* shift */init[/* shift */2]
              ],
              /* simRate */model[/* simRate */1]
            ];
    } else {
      var init$1 = model[/* person */0];
      return /* record */[
              /* person : record */[
                /* base_mood */model[/* person */0][/* base_mood */0] + 40 | 0,
                /* mood_swing */init$1[/* mood_swing */1],
                /* shift */init$1[/* shift */2]
              ],
              /* simRate */model[/* simRate */1]
            ];
    }
  } else {
    switch (msg.tag | 0) {
      case 0 : 
          var i = msg[0];
          console.log("SetShift : " + Pervasives.string_of_int(i));
          var init$2 = model[/* person */0];
          return /* record */[
                  /* person : record */[
                    /* base_mood */init$2[/* base_mood */0],
                    /* mood_swing */init$2[/* mood_swing */1],
                    /* shift */i
                  ],
                  /* simRate */model[/* simRate */1]
                ];
      case 1 : 
          return /* record */[
                  /* person */tickPerson(msg[0] * model[/* simRate */1] / 10, model[/* person */0]),
                  /* simRate */model[/* simRate */1]
                ];
      case 2 : 
          return /* record */[
                  /* person */model[/* person */0],
                  /* simRate */msg[0]
                ];
      
    }
  }
}

var initialModel = /* record */[
  /* person : record */[
    /* base_mood */75,
    /* mood_swing */100,
    /* shift */20
  ],
  /* simRate */1
];

var main = Interaction.interact(initialModel, view, update, /* Some */[/* tuple */[
        20,
        tick
      ]]);

var H = 0;

var inc = /* Inc */0;

var dec = /* Dec */1;

exports.H            = H;
exports.inc          = inc;
exports.dec          = dec;
exports.setShift     = setShift;
exports.tick         = tick;
exports.setSimRate   = setSimRate;
exports.viewPerson   = viewPerson;
exports.view         = view;
exports.tickPerson   = tickPerson;
exports.update       = update;
exports.initialModel = initialModel;
exports.main         = main;
/* main Not a pure module */
