// Generated by BUCKLESCRIPT VERSION 1.10.3, PLEASE EDIT WITH CARE
'use strict';

var Interaction           = require("interactive-pictures/src/interaction.js");
var Draw_ex$PhysicsSunset = require("./draw_ex.bs.js");

function updatePerson(t, p) {
  var delta = 100 * Math.sin(t / 250) | 0;
  return /* record */[
          /* base_mood */p[/* base_mood */0],
          /* mood_swing */delta,
          /* shift */p[/* shift */2]
        ];
}

var main = Interaction.simulate(Draw_ex$PhysicsSunset.initialPerson, Draw_ex$PhysicsSunset.view, updatePerson, 10.0);

var Draw = 0;

var initialPerson = Draw_ex$PhysicsSunset.initialPerson;

var view = Draw_ex$PhysicsSunset.view;

exports.Draw          = Draw;
exports.initialPerson = initialPerson;
exports.view          = view;
exports.updatePerson  = updatePerson;
exports.main          = main;
/* main Not a pure module */
