// Generated by BUCKLESCRIPT VERSION 1.10.3, PLEASE EDIT WITH CARE
'use strict';

var Web_document         = require("bucklescript-tea/src/web_document.js");
var Sunset$PhysicsSunset = require("./sunset.bs.js");

var app = Sunset$PhysicsSunset.main(Web_document.getElementById("root"));

app(/* () */0);

exports.app = app;
/* app Not a pure module */
